services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    networks:
      - nwfg-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - nwfg-network
    restart: always

  users-service:
    build:
      context: ./services/users-service
    container_name: users-service
    ports:
      - "4001:4001"
    env_file:
      - ./env/users.env
    depends_on:
      - redpanda
    networks:
      - nwfg-network
    restart: always
  rates-service:
    build:
      context: ./services/rates-service
      dockerfile: Dockerfile
    container_name: rates-service
    ports:
      - "4002:4002"
    env_file:
      - ./env/rates.env
    depends_on:
      - redpanda
      - redis
    networks:
      - nwfg-network
    restart: always

  upload-service:
    build:
      context: ./services/upload-service
    container_name: upload-service
    ports:
      - "4005:4005"
    env_file:
      - ./env/upload.env # <--- Apuntando a la carpeta central
    volumes:
      - ./services/upload-service:/app
      - /app/node_modules
    depends_on:
      - rates-service
      - users-service
    networks:
      - nwfg-network

  scripts-service:
    build:
      context: ./services/scripts-service
    container_name: scripts-service
    ports:
      - "4006:4006"
    env_file:
      - ./env/scripts.env
    depends_on:
      - redis
    networks:
      - nwfg-network
    restart: always

  graphql-gateway:
    build:
      context: ./services/graphql-gateway
    container_name: graphql-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./env/gateway.env
    depends_on:
      - scripts-service
    networks:
      - nwfg-network
    restart: always

networks:
  nwfg-network:
    driver: bridge
